apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: token-price-oracle/auth
          env:
            - name: JWT_KEY
              value: "hJ4RtYnggWrs@rt45DF$hhvv87"
            - name: MONOGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: APP_PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
